//
//  OSCTCPClientNotification.swift
//  SwiftOSC Core • https://github.com/orchetect/swift-osc-core
//  © 2026 Steffan Andrews • Licensed under MIT License
//

/// A notification event generated by an OSC TCP client.
public enum OSCTCPClientNotification {
    /// The client successfully connected to the remote server.
    case connected

    /// The client was disconnected from the remote server.
    /// If the disconnection was a result of an error, the error will be non-nil.
    case disconnected(error: (any Error)?)
}

extension OSCTCPClientNotification: Equatable {
    public static func == (lhs: Self, rhs: Self) -> Bool {
        switch (lhs, rhs) {
        case (.connected, .connected):
            true

        case let (.disconnected(lhsError), .disconnected(rhsError)):
            lhsError?.localizedDescription == rhsError?.localizedDescription

        default:
            false
        }
    }
}

extension OSCTCPClientNotification: Hashable {
    public func hash(into hasher: inout Hasher) {
        switch self {
        // no associated values, hash as normal
        case .connected:
            hasher.combine(0)
        case let .disconnected(error):
            // combine 1 in has to distinguish from `.connected`
            hasher.combine(1)
            // combine error.localizedDescription in hash to distinguish errors
            hasher.combine(error?.localizedDescription)
        }
    }
}

extension OSCTCPClientNotification: Sendable { }
