//
//  OSCTCPServerNotification.swift
//  SwiftOSC Core • https://github.com/orchetect/swift-osc-core
//  © 2026 Steffan Andrews • Licensed under MIT License
//

/// A notification event generated by the TCP server.
public enum OSCTCPServerNotification {
    /// The server accepted a connection from a remote client.
    case connected(remoteHost: String, remotePort: UInt16, clientID: OSCTCPClientSessionID)
    
    /// The server was notified that a remote client connection has closed.
    /// If the disconnection was a result of an error, the error will be non-nil.
    case disconnected(remoteHost: String, remotePort: UInt16, clientID: OSCTCPClientSessionID, error: (any Error)?)
}

extension OSCTCPServerNotification: Equatable {
    public static func == (lhs: Self, rhs: Self) -> Bool {
        switch (lhs, rhs) {
        case let (
            .connected(lhsHost, lhsPort, lhsClientID),
            .connected(rhsHost, rhsPort, rhsClientID)
        ):
            // if all variables the same then true (notifications are equal), else false
            (lhsHost == rhsHost)
                && (lhsPort == rhsPort)
                && (lhsClientID == rhsClientID)
        
        case let (
            .disconnected(lhsHost, lhsPort, lhsClientID, lhsError),
            .disconnected(rhsHost, rhsPort, rhsClientID, rhsError)
        ):
            // all variables (except error) must be the same to continue, else false
            (lhsHost == rhsHost)
                && (lhsPort == rhsPort)
                && (lhsClientID == rhsClientID)
                && (lhsError?.localizedDescription == rhsError?.localizedDescription)

        default:
            false
        }
    }
}

extension OSCTCPServerNotification: Hashable {
    public func hash(into hasher: inout Hasher) {
        switch self {
        case let .connected(host, port, id):
            // combine 0 to distinguish from `.disconnected`
            hasher.combine(0)
            // combine variables for unique hash
            hasher.combine(host)
            hasher.combine(port)
            hasher.combine(id)
        case let .disconnected(host, port, id, err):
            // combine 1 to distinguish from `.connected`
            hasher.combine(1)
            // combine variables for unique hash
            hasher.combine(host)
            hasher.combine(port)
            hasher.combine(id)
            hasher.combine(err?.localizedDescription)
        }
    }
}

extension OSCTCPServerNotification: Sendable { }
